from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from app.core.config import settings
from app.schemas.chat import ChatRequest, ChatResponse
import json

# Setup LLM
llm = ChatOpenAI(
    api_key=settings.OPENROUTER_API_KEY,
    base_url=settings.OPENAI_API_BASE,
    model="openai/gpt-4o-mini"
)

def run_orchestrator(request: ChatRequest) -> ChatResponse:
    messages = [{"role": m.role, "content": m.content} for m in request.messages]
    
    if request.mode == "b2c":
        system_prompt = """You are a Mixologist Agent for B2C users. 
Your goal is to help users find the perfect cocktail or bar based on their mood and preferences.
Use friendly, engaging language. If the user's request is vague, ask clarifying questions (Ask). 
If you have enough information, recommend a cocktail or venue and provide a ✨ Rationale for your choice.
Format your final response cleanly."""
    else:
        system_prompt = """You are a Master Bartender Agent for B2B users.
Your goal is to help bartenders create menus, calculate costs, and find ingredient substitutions.
Always be precise and professional. If asked about cost, estimate based on standard volumes (e.g., 30ml spirit = ~15000 VND).
Provide a ✨ Rationale for any substitution or recipe change."""

    messages.insert(0, {"role": "system", "content": system_prompt})
    
    try:
        response = llm.invoke(messages)
        return ChatResponse(
            response=response.content,
            rationale="Generated by AI based on your request context.",
            data={"mode": request.mode}
        )
    except Exception as e:
        return ChatResponse(
            response=f"Error connecting to AI service: {str(e)}",
            rationale=None,
            data=None
        )
